services:
  mongodb:
    image: mongo:6
    environment:
      MONGO_INITDB_ROOT_USERNAME: scraper
      MONGO_INITDB_ROOT_PASSWORD: scraper
      MONGO_INITDB_DATABASE: therapyfinder
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: ["--bind_ip_all", "--auth"]
    healthcheck:
      test: |
        mongosh --eval "
        db = db.getSiblingDB('admin');
        db.auth('scraper', 'scraper');
        db.adminCommand('ping')
        " --quiet
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  therapyfinder_scraper:
    build: ./therapyfinder_scraper
    container_name: therapyfinder_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: therapyfinder_scraper_final
      MONGO_USER: scraper
      MONGO_PASSWORD: scraper
      API_URL: https://therapyfinder.com/api/clinicians
      SCRAPE_LIMIT: 0
    volumes:
      - ./therapyfinder_scraper:/app
    command: tail -f /dev/null
    deploy:
      replicas: 0

  headway_scraper:
    build: ./headway_scraper
    container_name: headway_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: headway_scraper_final
      MONGO_USER: scraper
      MONGO_PASSWORD: scraper
      SCRAPE_LIMIT: 0
    volumes:
      - ./headway_scraper:/app
      - ./exports:/app/exports
    command: tail -f /dev/null

  rula_scraper:
    build: ./rula_scraper
    container_name: rula_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: rula_scraper_final
      MONGO_USER: scraper
      MONGO_PASSWORD: scraper
      HEADLESS: true
      SCRAPE_LIMIT: 0
    volumes:
      - ./rula_scraper:/app
      - ./exports:/app/exports
    command: tail -f /dev/null
    deploy:
      replicas: 0

  rula_basic_scraper:
    build: ./rula_scraper
    container_name: rula_basic_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: rula_scraper_final
      MONGO_USER: scraper
      MONGO_PASSWORD: scraper
      HEADLESS: true
      SCRAPE_MODE: basic
    volumes:
      - ./rula_scraper:/app
    command: node scrape_basic.js

  rula_detail_scraper:
    build: ./rula_scraper
    container_name: rula_detail_scraper
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_HOST: mongodb
      MONGO_PORT: 27017
      MONGO_DB: rula_scraper_final
      MONGO_USER: scraper
      MONGO_PASSWORD: scraper
      HEADLESS: true
      SCRAPE_MODE: detail
    volumes:
      - ./rula_scraper:/app
    command: node scrape_detail.js
volumes:
  mongodb_data:
